### ISSUE TITLE
Katacoda Scenario for windows users

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes-sigs/contributor-katacoda#5]
The present scenario hosted here is for users working on Linux environment, we would also like to have such scenarios for windows users, as most of the first-time contributors, especially students tend to use windows. 
But at present, the katacoda only supports [these scenarios](https://katacoda.com/scenario-examples/courses/environment-usages), which doesn't include windows. Still, there are options to create a custom environment.

**Comment by chris-short** [comment]
From O'Reilly: "They said we are not supporting Windows environments and currently do not have plans to."

**Comment by chris-short** [comment]
@Debanitrkl Did you say there was another option?

**Comment by Debanitrkl** [comment]
Only option I Could see now is trying make a custom scenario
