### ISSUE TITLE
Katacoda Scenario for k/website

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes-sigs/contributor-katacoda#9]
Implement these in katacoda scenario:
1. https://github.com/kubernetes/website#running-the-website-using-a-container
2. https://github.com/kubernetes/website#running-the-website-locally-using-hugo
3. https://github.com/kubernetes/website#building-the-api-reference-pages

**Comment by Debanitrkl** [comment]
Folks interested to work on this should consider applying to [LFX-Mentorship](https://mentorship.lfx.linuxfoundation.org/project/682ea527-4a16-4310-b104-aa00a15d1786) for the Spring'22

**Comment by rgrupesh** [comment]
@Debanitrkl  I just submitted my application through LFX website. Looking forward to working on this project this Spring. In the meantime, where can I learn more about this project? 

I went though the [issue](https://github.com/kubernetes/community/issues/5576) and the [contributor guidelines](https://github.com/kubernetes-sigs/contributor-katacoda) as well as created my first scenario with the help of this [website](https://katacoda.com/scenario-examples).

**Comment by Debanitrkl** [comment]
@rgrupesh all details about this project are already available in the readme also if you have any specific doubts you are free to ask them in #sig-contribex in K8s slack

**Comment by rgrupesh** [comment]
Sure! I'll ask if I get stuck somewhere. Thank you @Debanitrkl for the information.

**Comment by haru-02** [comment]
hi, can i take up this issue to work on ?

**Comment by haru-02** [comment]
Hi @Debanitrkl,
can i take this issue to work on ?

**Comment by Debanitrkl** [comment]
@haru-02 sure you could assign it to yourself and work on this, but since there are 3 different scenarios here please pick up one

**Comment by Debanitrkl** [comment]
> Folks interested to work on this should consider applying to [LFX-Mentorship](https://mentorship.lfx.linuxfoundation.org/project/682ea527-4a16-4310-b104-aa00a15d1786) for the Spring'22

Also see this, there will be a mentee soon to manage and work on this katacoda scenarios

**Comment by rgrupesh** [comment]
@Debanitrkl I have been working on to implement [running-the-website-locally-using-hugo](https://github.com/kubernetes/website#running-the-website-locally-using-hugo) for last few days. I forgot to assign myself.

**Comment by anubha-v-ardhan** [comment]
>Also see this, there will be a mentee soon to manage and work on this katacoda scenarios

@Debanitrkl Can I still help making a scenario now that a mentee is selected. If yes, I would like to give https://github.com/kubernetes/website#building-the-api-reference-pages a try.

**Comment by Debanitrkl** [comment]
> > Also see this, there will be a mentee soon to manage and work on this katacoda scenarios
> 
> @Debanitrkl Can I still help making a scenario now that a mentee is selected. If yes, I would like to give https://github.com/kubernetes/website#building-the-api-reference-pages a try.

Yeah sure fell free to work on it

**Comment by Debanitrkl** [comment]
@rgrupesh @anubha-v-ardhan any progress on this??

**Comment by rgrupesh** [comment]
I have not been working lately on this issue. Can you please take this @anubha-v-ardhan?
